### ISSUE TITLE
Runtime Exception: NPArray does not have method save

### ISSUE THREAD

**Issue by jdmg94** [shangar21/anime_upscaler#5]
Thanks for this project it seems very promising and I am very excited to restore some of my childhood animes. However I've stumbled on an issue after cloning the repo and installing its requirements.txt (which has a conflict on Pillow versions btw)

Now when I run the script it succesfully extract the frames but once it gets to upscaling it fails on this line:

https://github.com/shangar21/anime_upscaler/blob/main/anime_upscaler.py#L77

I digged a bit through the code and it seems like the issues is that on `upscale_slice` it returns a `nparray` instead of an `Image`

**Comment by shangar21** [comment]
Thnks for letting me know, in fact it helped me find another issue with the audio kind of screwing up the video output as well somehow when using moviepy and thus I changed to an ffmpeg subprocess call instead. Will merge the fix soon

**Comment by shangar21** [comment]
Closing issue as PR with ffmpeg is merged
